// packages/vue/src/CommandPalette/CommandPalette.vue
<script setup lang="ts">
import {
	moveCommandSelection,
	updateCommandHistory,
} from '@tweeq/core'
import {useEventListener} from '@vueuse/core'
import {search} from 'fast-fuzzy'
import {computed, ref, useTemplateRef, watch} from 'vue'

import {BindIcon} from '../BindIcon'
import {Icon} from '../Icon'
import {type ActionItemOptions, useActionsStore} from '../stores/actions'
import {useAppConfigStore} from '../stores/appConfig'

const actions = useActionsStore()

const $popover = useTemplateRef('$popover')
const searchWord = ref('')

const appConfig = useAppConfigStore()

const performedActionsHistory = appConfig.ref<string[]>(
	'commandPalette.performedActionsHistory',
	[]
)

const open = ref(false)

useEventListener($popover, 'toggle', (e: ToggleEvent) => {
	open.value = e.newState === 'open'
})

watch(
	open,
	open => {
		searchWord.value = ''
		if (open) {
			$popover.value?.querySelector('input')?.focus()
		}
	},
	{immediate: true}
)

const filteredActions = computed(() => {
	if (searchWord.value === '' && open.value) {
		return performedActionsHistory.value
			.map(id => actions.allActions[id])
			.filter(action => action !== undefined)
	}

	return search(searchWord.value, Object.values(actions.allActions), {
		keySelector: action => action.label,
	})
})

const selectedAction = ref<null | ActionItemOptions>(null)

watch(filteredActions, () => {
	if (filteredActions.value.length > 0) {
		selectedAction.value = filteredActions.value[0]
	} else {
		selectedAction.value = null
	}
})

useEventListener(typeof window === 'undefined' ? null : window, 'keydown', e => {
	if (!(e.metaKey || e.ctrlKey) || e.key.toLowerCase() !== 'p') return
	e.preventDefault()
	$popover.value?.togglePopover()
})

function onKeydown(e: KeyboardEvent) {
	if (selectedAction.value && (e.key === 'ArrowDown' || e.key === 'ArrowUp')) {
		e.preventDefault()
		const index = filteredActions.value.indexOf(selectedAction.value as any)
		const length = filteredActions.value.length

		const move = e.key === 'ArrowDown' ? 1 : -1

		const newIndex = moveCommandSelection(index, move, length)
		selectedAction.value = filteredActions.value[newIndex]
	}

	if (e.key === 'Enter' && selectedAction.value) {
		perform(selectedAction.value as ActionItemOptions)
	}
}

function perform(action: ActionItemOptions) {
	performedActionsHistory.value = updateCommandHistory(
		performedActionsHistory.value,
		action.id
	)

	$popover.value?.hidePopover()
	void actions.perform(action.id)
}
</script>

<template>
	<div ref="$popover" class="TqCommandPalette" popover>
		<div class="searchContainer">
			<Icon class="search-icon" icon="material-symbols:search-rounded" />
			<input
				v-model="searchWord"
				class="search"
				type="text"
				placeholder="Search menus and commands"
				@keydown="onKeydown"
			/>
		</div>
		<div
			v-if="searchWord === '' && filteredActions.length > 0"
			class="recentActions"
		>
			Recent Actions
		</div>
		<ul>
			<li
				v-for="action in filteredActions"
				:key="action.id"
				class="action"
				:class="{selected: action === selectedAction}"
				@pointermove="selectedAction = action"
				@click="perform(action)"
			>
				<Icon class="action-icon" :icon="action.icon ?? ''" />
				<span class="action-label">{{ action.label }}</span>
				<BindIcon
					v-if="action.bind?.icon"
					:icon="action.bind.icon"
					class="action-bind-icon"
				/>
			</li>
		</ul>
	</div>
</template>

<!--
	The popover is promoted to the top layer and rendered outside .TqViewport,
	so it misses Tweeq's viewport reset (font-family, etc.) and falls back to
	the UA serif font. Apply the reset here, unscoped — same as PaneModal.
-->
<style lang="stylus">

reset-viewport('.TqCommandPalette')
</style>

<style lang="stylus" scoped>

.TqCommandPalette
	width 400px
	top 20vh
	margin 0 auto
	border-radius 8px
	background var(--tq-color-surface)
	border 1px solid var(--tq-color-border)
	backdrop-filter blur(4px)
	padding 0 9px
	box-shadow 0 0 30px 0 var(--tq-color-shadow)

.searchContainer
	display flex
	align-items center
	gap var(--tq-gap-related)
	padding-left 3px

.search-icon
	display block

.search
	display block
	flex-grow 1
	font-size calc(1.2 * var(--tq-rem))
	height 48px
	line-height 36px

	&::placeholder
		font-size calc(1.2 * var(--tq-rem))
		opacity .3

.recentActions
	padding 0 6px 9px
	font-weight bold
	opacity .8

.action
	display flex
	align-items center
	gap var(--tq-gap-section)
	line-height 32px
	border-radius 3px
	padding 0 6px

	&:last-child
		margin-bottom 9px

	&.selected
		background var(--tq-color-accent)
		color var(--tq-color-on-accent)

.action-icon
	width 20px

.action-label
	flex-grow 1

.action-bind-icon
	opacity .5
	font-size 1.1em
</style>

// packages/react/src/components/CommandPalette/CommandPalette.tsx
import './CommandPalette.global.styl'

import {
	moveCommandSelection,
	updateCommandHistory,
} from '@tweeq/core'
import {type ActionItem, actionsStore, appConfigStore} from '@tweeq/dom'
import {search} from 'fast-fuzzy'
import {useEffect, useMemo, useRef, useState} from 'react'
import {useStore} from 'zustand'

import {classNames} from '../../classNames'
import {useConfigRef, useEventListener} from '../../hooks'
import {BindIcon} from '../BindIcon'
import {Icon} from '../Icon'
import styles from './CommandPalette.module.styl'

const historyEntry = appConfigStore
	.getState()
	.ref<string[]>('commandPalette.performedActionsHistory', [])

export function CommandPalette() {
	const root = useRef<HTMLDivElement>(null)
	const input = useRef<HTMLInputElement>(null)
	const allActions = useStore(actionsStore, state => state.allActions)
	const [history, setHistory] = useConfigRef(historyEntry)
	const [open, setOpen] = useState(false)
	const [query, setQuery] = useState('')
	const filtered = useMemo(() => {
		if (query === '' && open) {
			return history
				.map(id => allActions[id])
				.filter((action): action is ActionItem => action !== undefined)
		}
		return search(query, Object.values(allActions), {
			keySelector: action => action.label,
		})
	}, [allActions, history, open, query])
	const [selectedId, setSelectedId] = useState<string | null>(null)
	const selected =
		filtered.find(action => action.id === selectedId) ?? filtered[0] ?? null

	useEventListener<ToggleEvent>(root, 'toggle', event => {
		setOpen(event.newState === 'open')
	})
	useEventListener<KeyboardEvent>(
		typeof window === 'undefined' ? null : window,
		'keydown',
		event => {
			if (
				!(event.metaKey || event.ctrlKey) ||
				event.key.toLowerCase() !== 'p'
			) {
				return
			}
			event.preventDefault()
			try {
				root.current?.togglePopover()
			} catch {
				// Native popover unavailable.
			}
		}
	)
	useEffect(() => {
		setQuery('')
		setSelectedId(null)
		if (open) requestAnimationFrame(() => input.current?.focus())
	}, [open])

	const perform = (action: ActionItem) => {
		setHistory(current => updateCommandHistory(current, action.id))
		root.current?.hidePopover()
		void actionsStore.getState().perform(action.id)
	}

	return (
		<div
			ref={root}
			className={classNames('TqCommandPalette', styles.commandPalette)}
			popover="auto"
		>
			<div className={styles.searchContainer}>
				<Icon
					className={styles.searchIcon}
					icon="material-symbols:search-rounded"
				/>
				<input
					ref={input}
					className={styles.search}
					type="text"
					placeholder="Search menus and commands"
					value={query}
					onChange={event => setQuery(event.currentTarget.value)}
					onKeyDown={event => {
						if (
							selected &&
							(event.key === 'ArrowDown' || event.key === 'ArrowUp')
						) {
							event.preventDefault()
							const index = filtered.indexOf(selected)
							const next = moveCommandSelection(
								index,
								event.key === 'ArrowDown' ? 1 : -1,
								filtered.length
							)
							setSelectedId(filtered[next].id)
						} else if (event.key === 'Enter' && selected) {
							perform(selected)
						}
					}}
				/>
			</div>
			{query === '' && filtered.length > 0 && (
				<div className={styles.recentActions}>Recent Actions</div>
			)}
			<ul>
				{filtered.map(action => (
					<li
						key={action.id}
						className={classNames(
							styles.action,
							action === selected && styles.selected
						)}
						onPointerMove={() => setSelectedId(action.id)}
						onClick={() => perform(action)}
					>
						{action.icon ? (
							<Icon className={styles.actionIcon} icon={action.icon} />
						) : (
							<span className={styles.actionIcon} />
						)}
						<span className={styles.actionLabel}>{action.label}</span>
						{action.bind?.icon && (
							<BindIcon
								className={styles.actionBindIcon}
								icon={action.bind.icon}
							/>
						)}
					</li>
				))}
			</ul>
		</div>
	)
}
