// packages/vue/src/InputColor/InputColorChannelValues.vue
<script setup lang="ts">
import {computed, ref} from 'vue'

import {InputDropdown} from '../InputDropdown'
import {InputGroup} from '../InputGroup'
import {InputNumber} from '../InputNumber'
import {InputString} from '../InputString'
import * as V from '@tweeq/core/validator'
import {type ColorChannel, type ColorSpace, HSVA} from './types'
import {hsv2rgb, setHSVAChannel} from './utils'

interface Props {
	colorCode: string
	hsva: HSVA
	alpha?: boolean
	disabled?: boolean
}

const props = withDefaults(defineProps<Props>(), {alpha: true})

const emit = defineEmits<{
	'update:colorCode': [string]
	'update:hsva': [HSVA]
}>()

const colorSpace = ref<ColorSpace>('hsv')

const rgb = computed(() => hsv2rgb(props.hsva))

function onUpdateChannel(channel: ColorChannel, value: number) {
	const newColor = setHSVAChannel(props.hsva, channel, value)

	emit('update:hsva', newColor)
}
</script>

<template>
	<InputGroup
		class="InputColorChannelValues"
		data-tq-component="input-color-channel-values"
		data-tq-part="root"
	>
		<InputDropdown
			v-model="colorSpace"
			class="color-space"
			data-tq-part="color-space"
			theme="minimal"
			:disabled="props.disabled"
			:options="['rgb', 'hsv', 'hex']"
			:labelizer="s => s.toUpperCase()"
		/>
		<InputGroup v-if="colorSpace === 'rgb'" class="channel" data-tq-part="channel">
			<InputNumber
				:modelValue="rgb.r * 255"
				:min="0"
				:max="255"
				:precision="0"
				:bar="false"
				:disabled="props.disabled"
				inline-position="start"
				@update:modelValue="onUpdateChannel('r', $event / 255)"
			/>
			<InputNumber
				:modelValue="rgb.g * 255"
				:min="0"
				:max="255"
				:precision="0"
				:bar="false"
				:disabled="props.disabled"
				inline-position="middle"
				@update:modelValue="onUpdateChannel('g', $event / 255)"
			/>
			<InputNumber
				:modelValue="rgb.b * 255"
				:min="0"
				:max="255"
				:precision="0"
				:bar="false"
				:disabled="props.disabled"
				:inline-position="props.alpha ? 'middle' : 'end'"
				@update:modelValue="onUpdateChannel('b', $event / 255)"
			/>
			<InputNumber
				v-if="props.alpha"
				:modelValue="hsva.a * 100"
				:min="0"
				:max="100"
				:precision="0"
				:bar="false"
				:disabled="props.disabled"
				suffix="%"
				inline-position="end"
				@update:modelValue="onUpdateChannel('a', $event / 100)"
			/>
		</InputGroup>
		<InputGroup v-else-if="colorSpace === 'hsv'" class="channel" data-tq-part="channel">
			<InputNumber
				:modelValue="hsva.h * 360"
				:min="0"
				:max="360"
				:precision="0"
				:bar="false"
				:disabled="props.disabled"
				suffix="°"
				inline-position="start"
				@update:modelValue="onUpdateChannel('h', $event / 360)"
			/>
			<InputNumber
				:modelValue="hsva.s * 100"
				:min="0"
				:max="100"
				:precision="0"
				:bar="false"
				:disabled="props.disabled"
				suffix="%"
				inline-position="middle"
				@update:modelValue="onUpdateChannel('s', $event / 100)"
			/>
			<InputNumber
				:modelValue="hsva.v * 100"
				:min="0"
				:max="100"
				:precision="0"
				:bar="false"
				:disabled="props.disabled"
				suffix="%"
				:inline-position="props.alpha ? 'middle' : 'end'"
				@update:modelValue="onUpdateChannel('v', $event / 100)"
			/>
			<InputNumber
				v-if="props.alpha"
				:modelValue="hsva.a * 100"
				:min="0"
				:max="100"
				:precision="0"
				:bar="false"
				:disabled="props.disabled"
				suffix="%"
				inline-position="end"
				@update:modelValue="onUpdateChannel('a', $event / 100)"
			/>
		</InputGroup>
		<InputString
			v-else-if="colorSpace === 'hex'"
			font="monospace"
			class="channel"
			data-tq-part="channel"
			:modelValue="colorCode"
			:validator="V.colorCode"
			:disabled="props.disabled"
			@update:modelValue="emit('update:colorCode', $event)"
		/>
	</InputGroup>
</template>

// packages/react/src/components/InputColor/InputColorChannelValues.tsx
import {
	type ColorChannel,
	type ColorSpace,
	hsv2rgb,
	type HSVA,
	setHSVAChannel,
	validator,
} from '@tweeq/core'

import {InputDropdown} from '../InputDropdown'
import {InputGroup} from '../InputGroup'
import {InputNumber} from '../InputNumber'
import {InputString} from '../InputString'
import {useInputColorContext} from './InputColorContext'

const COLOR_SPACES: ColorSpace[] = ['rgb', 'hsv', 'hex']

export interface InputColorChannelValuesProps {
	colorCode: string
	onChangeColorCode?: (value: string) => void
	value: HSVA
	onChange?: (value: HSVA) => void
	alpha?: boolean
	disabled?: boolean
}

export function InputColorChannelValues({
	colorCode,
	onChangeColorCode,
	value,
	onChange,
	alpha = true,
	disabled,
}: InputColorChannelValuesProps) {
	const {colorSpace, setColorSpace} = useInputColorContext()
	const rgb = hsv2rgb(value)
	const update = (channel: ColorChannel, next: number) =>
		onChange?.(setHSVAChannel(value, channel, next))

	return (
		<InputGroup
			data-tq-component="input-color-channel-values"
			data-tq-part="root"
		>
			<InputDropdown
				data-tq-part="color-space"
				theme="minimal"
				disabled={disabled}
				value={colorSpace}
				onChange={setColorSpace}
				options={COLOR_SPACES}
				labelizer={space => space.toUpperCase()}
			/>
			{colorSpace === 'rgb' && (
				<InputGroup data-tq-part="channel">
					<InputNumber
						value={rgb.r * 255}
						min={0}
						max={255}
						precision={0}
						bar={false}
						disabled={disabled}
						onChange={next => update('r', next / 255)}
					/>
					<InputNumber
						value={rgb.g * 255}
						min={0}
						max={255}
						precision={0}
						bar={false}
						disabled={disabled}
						onChange={next => update('g', next / 255)}
					/>
					<InputNumber
						value={rgb.b * 255}
						min={0}
						max={255}
						precision={0}
						bar={false}
						disabled={disabled}
						onChange={next => update('b', next / 255)}
					/>
					{alpha && (
						<InputNumber
							value={value.a * 100}
							min={0}
							max={100}
							precision={0}
							bar={false}
							disabled={disabled}
							suffix="%"
							onChange={next => update('a', next / 100)}
						/>
					)}
				</InputGroup>
			)}
			{colorSpace === 'hsv' && (
				<InputGroup data-tq-part="channel">
					<InputNumber
						value={value.h * 360}
						min={0}
						max={360}
						precision={0}
						bar={false}
						disabled={disabled}
						suffix="°"
						onChange={next => update('h', next / 360)}
					/>
					<InputNumber
						value={value.s * 100}
						min={0}
						max={100}
						precision={0}
						bar={false}
						disabled={disabled}
						suffix="%"
						onChange={next => update('s', next / 100)}
					/>
					<InputNumber
						value={value.v * 100}
						min={0}
						max={100}
						precision={0}
						bar={false}
						disabled={disabled}
						suffix="%"
						onChange={next => update('v', next / 100)}
					/>
					{alpha && (
						<InputNumber
							value={value.a * 100}
							min={0}
							max={100}
							precision={0}
							bar={false}
							disabled={disabled}
							suffix="%"
							onChange={next => update('a', next / 100)}
						/>
					)}
				</InputGroup>
			)}
			{colorSpace === 'hex' && (
				<InputString
					data-tq-part="channel"
					font="monospace"
					value={colorCode}
					validator={validator.colorCode}
					disabled={disabled}
					onChange={onChangeColorCode}
				/>
			)}
		</InputGroup>
	)
}
