// packages/react/src/components/InputVec/InputVec.tsx
import {type InputEvents, type InputProps} from '../../core'
import {InputGroup} from '../InputGroup'
import {InputNumber} from '../InputNumber'

export interface InputVecProps<T extends readonly number[]>
	extends InputProps,
		InputEvents {
	value: T
	onChange?: (value: T) => void
	min?: T | number
	max?: T | number
	step?: T | number
	icon?: string[] | string
}

function valueAt<T extends readonly number[]>(
	value: T | number | undefined,
	index: number
): number | undefined {
	return Array.isArray(value) ? value[index] : value
}

export function InputVec<T extends readonly number[]>({
	value,
	onChange,
	min,
	max,
	step,
	icon,
	disabled,
	invalid,
	onFocus,
	onBlur,
	onConfirm,
}: InputVecProps<T>) {
	let pending: number[] | undefined
	let confirmPending = false

	const commitChange = (index: number, next: number) => {
		if (!pending) {
			pending = [...value]
			queueMicrotask(() => {
				if (pending) onChange?.(pending as unknown as T)
				pending = undefined
			})
		}
		pending[index] = next
	}
	const commitConfirm = () => {
		if (confirmPending) return
		confirmPending = true
		queueMicrotask(() => {
			confirmPending = false
			onConfirm?.()
		})
	}

	return (
		<InputGroup>
			{value.map((entry, index) => (
				<InputNumber
					key={index}
					value={entry}
					min={valueAt(min, index)}
					max={valueAt(max, index)}
					step={valueAt(step, index)}
					leftIcon={Array.isArray(icon) ? icon[index] : icon}
					disabled={disabled}
					invalid={invalid}
					onChange={next => commitChange(index, next)}
					onFocus={onFocus}
					onBlur={onBlur}
					onConfirm={commitConfirm}
				/>
			))}
		</InputGroup>
	)
}

// packages/vue/src/InputVec/InputVec.vue
<script setup lang="ts" generic="T extends readonly number[]">
import {nextTick} from 'vue'

import {InputGroup} from '../InputGroup'
import {InputNumber} from '../InputNumber'
import {InputEmits} from '../types'
import {InputVecProps} from './types'

const model = defineModel<T>({required: true})

const props = defineProps<InputVecProps<T>>()

const emit = defineEmits<InputEmits>()

function minAt(i: number): number | undefined {
	return Array.isArray(props.min) ? props.min[i] : (props.min as number | undefined)
}

function maxAt(i: number): number | undefined {
	return Array.isArray(props.max) ? props.max[i] : (props.max as number | undefined)
}

function stepAt(i: number): number | undefined {
	return Array.isArray(props.step)
		? props.step[i]
		: (props.step as number | undefined)
}

function leftIconAt(i: number) {
	return Array.isArray(props.icon) ? props.icon[i] : props.icon
}

function inlinePositionAt(i: number) {
	return i === 0 ? 'start' : i === model.value.length - 1 ? 'end' : 'middle'
}

let changedModel: number[] | undefined

function commitChange(index: number, value: number) {
	if (!changedModel) {
		nextTick(() => {
			model.value = changedModel as unknown as T
			changedModel = undefined
		})

		changedModel = [...model.value]
	}

	changedModel[index] = value
}

let willConfirm = false
function commitConfirm() {
	if (!willConfirm) {
		nextTick(() => {
			emit('confirm')
			willConfirm = false
		})
	}
	willConfirm = true
}
</script>

<template>
	<InputGroup class="TqInputVec">
		<InputNumber
			v-for="(v, i) in model"
			:key="i"
			:min="minAt(i)"
			:max="maxAt(i)"
			:step="stepAt(i)"
			:leftIcon="leftIconAt(i)"
			:disabled="props.disabled"
			:invalid="props.invalid"
			:modelValue="v"
			:inline-position="inlinePositionAt(i)"
			@update:modelValue="commitChange(i, $event)"
			@focus="emit('focus')"
			@blur="emit('blur')"
			@confirm="commitConfirm()"
		/>
	</InputGroup>
</template>
