// packages/react/src/components/MultiSelectPopup/MultiSelectPad.tsx
import {type DragState, multiSelectStore} from '@tweeq/dom'
import {type vec2} from 'linearly'
import {useEffect, useMemo, useRef} from 'react'

import {useDrag, useKeys} from '../../hooks'
import {IconIndicator} from '../IconIndicator'

const PAD_KEYS = ['x', 'y', '1', '2'] as const

export interface MultiSelectPadProps {
	type: 'slider' | 'pad'
	update:
		| ((delta: number) => (values: number[]) => number[])
		| ((delta: vec2) => (values: number[]) => number[])
	icon: string
}

export function MultiSelectPad({type, update, icon}: MultiSelectPadProps) {
	const root = useRef<HTMLDivElement>(null)
	const keys = useKeys(PAD_KEYS)
	const keysRef = useRef(keys)
	keysRef.current = keys
	const updateRef = useRef(update)
	updateRef.current = update
	const typeRef = useRef(type)
	typeRef.current = type
	const origin = useRef<vec2>([0, 0])
	const previousConstraint = useRef(false)

	const options = useMemo(
		() => ({
			lockPointer: true,
			onDragStart(state: DragState) {
				multiSelectStore.getState().captureValues()
				origin.current = state.xy
			},
			onDrag(state: DragState) {
				let delta: vec2 = [
					state.xy[0] - origin.current[0],
					state.xy[1] - origin.current[1],
				]
				if (typeRef.current === 'slider') {
					const apply = (updateRef.current as MultiSelectPadProps['update'])(
						delta[0] as never
					)
					multiSelectStore.getState().updateValues(apply)
				} else {
					if (keysRef.current.x || keysRef.current['1']) delta = [delta[0], 0]
					else if (keysRef.current.y || keysRef.current['2'])
						delta = [0, delta[1]]
					const apply = (
						updateRef.current as (delta: vec2) => (values: number[]) => number[]
					)(delta)
					multiSelectStore.getState().updateValues(apply)
				}
			},
			onDragEnd() {
				multiSelectStore.getState().confirmValues()
			},
		}),
		[]
	)
	const drag = useDrag(root, options)

	useEffect(() => {
		const constrained = keys.x || keys.y || keys['1'] || keys['2']
		if (constrained && !previousConstraint.current) {
			multiSelectStore.getState().captureValues()
			origin.current = drag.xy
		}
		previousConstraint.current = constrained
	}, [drag.xy, keys])

	return (
		<div
			ref={root}
			data-tq-multi-select-action={type}
			data-tq-dragging={drag.dragging ? '' : undefined}
			data-tq-part="pad"
		>
			<IconIndicator icon={icon} active={drag.dragging} />
		</div>
	)
}

// packages/vue/src/MultiSelectPopup/MultiSelectPad.vue
<script setup lang="ts">
import {useMagicKeys} from '@vueuse/core'
import {vec2} from 'linearly'
import {computed, useTemplateRef, watch} from 'vue'

import {IconIndicator} from '../IconIndicator'
import {useMultiSelectStore} from '../stores/multiSelect'
import {useDrag} from '../use/useDrag'

const props = defineProps<{
	type: 'slider' | 'pad'
	updator:
		| ((delta: number) => (values: number[]) => number[])
		| ((delta: vec2) => (values: number[]) => number[])
	icon: string
}>()

const multiSelect = useMultiSelectStore()

const $root = useTemplateRef('$root')

let origin: vec2 = vec2.zero

const {x, y, '1': d1, '2': d2} = useMagicKeys()

const constrainsX = computed(() => x.value || d1.value)
const constrainsY = computed(() => y.value || d2.value)

watch(
	[constrainsX, constrainsY],
	([x, y]) => {
		if (x || y) {
			multiSelect.captureValues()
			origin = xy.value
		}
	},
	{flush: 'sync'}
)

const {xy, dragging} = useDrag($root, {
	lockPointer: true,
	onDragStart({xy}) {
		multiSelect.captureValues()
		origin = xy
	},
	onDrag({xy}) {
		let delta = vec2.sub(xy, origin)
		if (props.type === 'slider') {
			const f = props.updator(delta[0] as any)
			multiSelect.updateValues(f)
		} else {
			if (constrainsX.value) {
				delta = vec2.mul(delta, [1, 0])
			} else if (constrainsY.value) {
				delta = vec2.mul(delta, [0, 1])
			}

			const f = props.updator(delta as any)
			multiSelect.updateValues(f)
		}
	},
	onDragEnd() {
		multiSelect.confirmValues()
	},
})
</script>

<template>
	<IconIndicator
		ref="$root"
		class="TqMultiSelectPad"
		:icon="icon"
		:active="dragging"
		:data-tq-multi-select-action="type"
		:data-tq-dragging="dragging ? '' : undefined"
		data-tq-part="pad"
	/>
</template>
