// src/react/components/InputRotary/InputRotary.tsx
import {scalar, vec2} from 'linearly'
import {range} from 'lodash-es'
import {
	type ButtonHTMLAttributes,
	useEffect,
	useId,
	useMemo,
	useRef,
	useState,
} from 'react'
import {useStore} from 'zustand'

import {
	clampPosWithinRect,
	type DragState,
	getRotaryDragValue,
	type InputBoxProps,
	type InputEvents,
	mergeSvgPaths,
	type Rect,
	signedAngleBetween,
	svgArc,
	svgCircle,
	svgLine,
	themeStore,
	unsignedMod,
} from '../../../core'
import {classNames} from '../../classNames'
import {
	useCopyPaste,
	useCursorStyle,
	useDrag,
	useElementCenter,
	useKeys,
	useLastActive,
	useMultiSelect,
	useWindowSize,
} from '../../hooks'
import {SvgIcon} from '../SvgIcon'
import {Tooltip} from '../Tooltip'
import {TweakOverlay} from '../TweakOverlay'
import styles from './InputRotary.module.styl'

const ROTARY_KEYS = ['Shift', 'q', 'a', 'r'] as const

export interface InputRotaryProps
	extends InputBoxProps,
		InputEvents,
		Omit<
			ButtonHTMLAttributes<HTMLButtonElement>,
			'onBlur' | 'onChange' | 'onFocus' | 'value'
		> {
	value: number
	onChange?: (value: number) => void
	snap?: number
	angleOffset?: number
}

export function InputRotary({
	value,
	onChange,
	snap = 45,
	angleOffset = -90,
	disabled,
	invalid,
	inlinePosition,
	blockPosition,
	onFocus,
	onBlur,
	onConfirm,
	className,
	...props
}: InputRotaryProps) {
	const root = useRef<HTMLButtonElement>(null)
	const center = useElementCenter(root)
	const centerRef = useRef(center)
	centerRef.current = center
	const keys = useKeys(ROTARY_KEYS)
	const keysRef = useRef(keys)
	keysRef.current = keys
	const keyMode = useLastActive({absolute: keys.a, relative: keys.r})
	const [pointerMode, setPointerMode] = useState<'absolute' | 'relative'>(
		'relative'
	)
	const mode = keyMode ?? pointerMode
	const modeRef = useRef(mode)
	modeRef.current = mode
	const [local, setLocal] = useState(value)
	const localRef = useRef(local)
	localRef.current = local
	const valueRef = useRef(value)
	valueRef.current = value
	const initialValue = useRef(value)
	const inputHeight = useStore(themeStore, state => state.inputHeight)
	const snapRadii: vec2 = [inputHeight * 4, 160]
	const snapRadiiRef = useRef(snapRadii)
	snapRadiiRef.current = snapRadii
	const callbacksRef = useRef({
		onChange,
		onConfirm,
		onFocus,
		onBlur,
		disabled,
		snap,
		angleOffset,
	})
	callbacksRef.current = {
		onChange,
		onConfirm,
		onFocus,
		onBlur,
		disabled,
		snap,
		angleOffset,
	}
	const dragRef = useRef<DragState | null>(null)

	const multi = useMultiSelect({
		type: 'number',
		getElement: () => root.current,
		getValue: () => localRef.current,
		setValue: next => {
			const number = Number(next)
			setLocal(number)
			localRef.current = number
			callbacksRef.current.onChange?.(number)
		},
		confirm: () => callbacksRef.current.onConfirm?.(),
	})
	const multiRef = useRef(multi)
	multiRef.current = multi

	const dragOptions = useMemo(
		() => ({
			disabled: () => Boolean(callbacksRef.current.disabled),
			dragDelaySeconds: 0,
			onDragStart(state: DragState) {
				dragRef.current = state
				initialValue.current = valueRef.current
				let next = valueRef.current
				if (modeRef.current === 'absolute') {
					const point = vec2.sub(state.xy, centerRef.current)
					const angle = vec2.angle(point) - callbacksRef.current.angleOffset
					next += signedAngleBetween(angle, next)
				}
				setLocal(next)
				localRef.current = next
				multiRef.current.capture()
			},
			onDrag(state: DragState) {
				dragRef.current = state
				const rect = root.current?.getBoundingClientRect()
				const liveCenter: vec2 = rect
					? [rect.left + rect.width / 2, rect.top + rect.height / 2]
					: centerRef.current
				const point = vec2.sub(state.xy, liveCenter)
				const previous = vec2.sub(state.previous, liveCenter)
				const deltaAngle = vec2.angle(previous, point)
				const radius = vec2.dist(liveCenter, state.xy)
				const shouldSnap =
					keysRef.current.Shift ||
					keysRef.current.q ||
					(snapRadiiRef.current[0] <= radius &&
						radius <= snapRadiiRef.current[1])
				const next = getRotaryDragValue(
					localRef.current,
					deltaAngle,
					callbacksRef.current.snap,
					shouldSnap
				)
				setLocal(next.local)
				localRef.current = next.local
				callbacksRef.current.onChange?.(next.output)
				if (modeRef.current === 'absolute') {
					multiRef.current.update(() => next.output)
				} else {
					const delta = next.output - initialValue.current
					multiRef.current.update(other => {
						const updated = Number(other) + delta
						return shouldSnap
							? scalar.quantize(updated, callbacksRef.current.snap)
							: updated
					})
				}
			},
			onDragEnd() {
				callbacksRef.current.onConfirm?.()
				multiRef.current.confirm()
			},
		}),
		[]
	)
	const drag = useDrag(root, dragOptions)
	dragRef.current = drag
	useEffect(() => {
		if (!drag.dragging) {
			setLocal(value)
			localRef.current = value
		}
	}, [drag.dragging, value])
	useCursorStyle(drag.dragging ? 'none' : null)
	useCopyPaste({
		target: root,
		onCopy: () =>
			void navigator.clipboard.writeText(valueRef.current.toString()),
		onPaste: async () => {
			const pasted = parseFloat(await navigator.clipboard.readText())
			if (Number.isNaN(pasted)) return
			callbacksRef.current.onChange?.(pasted)
			multiRef.current.update(() => pasted)
			multiRef.current.confirm()
		},
	})

	const shouldSnap =
		keys.Shift ||
		keys.q ||
		(snapRadii[0] <= vec2.dist(center, drag.xy) &&
			vec2.dist(center, drag.xy) <= snapRadii[1])
	const windowSize = useWindowSize()
	const bounds: Rect = [
		[40, 40],
		[windowSize.width - 40, windowSize.height - 40],
	]
	const labelPosition = clampPosWithinRect(drag.initial, drag.xy, bounds)
	const display = `${Math.trunc(value / 360) ? `${Math.trunc(value / 360)}x ` : ''}${(
		value -
		Math.trunc(value / 360) * 360
	).toFixed(1)}°`
	const markerId = useId().replaceAll(':', '')
	const radialLine = (angle: number, inner: number, outer: number) => {
		const adjusted = angle + angleOffset
		return svgLine(
			vec2.dir(adjusted, inner, center),
			vec2.dir(adjusted, outer, center)
		)
	}
	const metersPath = mergeSvgPaths(
		range(0, 360, snap).map(angle => radialLine(angle, ...snapRadii))
	)
	const overlayPath = (() => {
		if (mode === 'absolute') {
			return radialLine(value, inputHeight, vec2.dist(center, drag.xy))
		}
		const baseRadius = inputHeight * 4
		const radiusStep = inputHeight * 0.25
		const start = initialValue.current + angleOffset
		const end = value + angleOffset
		const turns =
			Math.floor(Math.abs(end - start) / 360) * Math.sign(end - start)
		const revolutions = range(0, turns).map(index =>
			svgCircle(center, baseRadius + index * radiusStep)
		)
		let offsetInTurn = unsignedMod(signedAngleBetween(end, start), 360)
		if (end < start) offsetInTurn -= 360
		const startInTurn = unsignedMod(start, 360)
		const arc = svgArc(
			center,
			baseRadius + turns * radiusStep,
			startInTurn,
			startInTurn + offsetInTurn
		)
		return mergeSvgPaths([...revolutions, arc])
	})()
	const activeMeterPath =
		shouldSnap && value % snap === 0 ? radialLine(value, ...snapRadii) : ''

	return (
		<>
			<button
				{...props}
				ref={root}
				className={classNames(
					styles.tqInputRotary,
					drag.dragging && styles.tweaking,
					multi.subfocus && styles.subfocus,
					className
				)}
				type="button"
				disabled={disabled}
				aria-invalid={invalid || undefined}
				inline-position={inlinePosition}
				block-position={blockPosition}
				{...{'tweak-mode': mode}}
				onFocus={() => {
					multi.setFocusing(true)
					onFocus?.()
				}}
				onBlur={() => {
					multi.setFocusing(false)
					onBlur?.()
				}}
			>
				<SvgIcon mode="block" className={styles.rotary}>
					<circle className={styles.circle} cx="16" cy="16" r="16" />
					<g
						style={{
							transformOrigin: '16px 16px',
							transform: `rotate(${value + angleOffset}deg)`,
						}}
						onPointerEnter={() => setPointerMode('absolute')}
						onPointerLeave={() => !drag.dragging && setPointerMode('relative')}
					>
						<path
							className={styles.absoluteModeArea}
							d="M 16 16 L 16 32 A 16 16 0 0 0 16 0 Z"
						/>
						<path className={styles.tip} d="M20 16 L30 16" />
					</g>
				</SvgIcon>
			</button>
			{drag.dragging && (
				<TweakOverlay>
					<div className={styles.overlay}>
						<svg>
							<defs>
								<marker
									id={markerId}
									markerWidth="6"
									markerHeight="6"
									refX="3"
									refY="3"
									orient="auto"
									fill="var(--tq-color-accent)"
								>
									<path d="M 0 0 L 6 3 L 0 6 Z" />
								</marker>
							</defs>
							<path
								className={classNames(
									styles.thin,
									styles.gray,
									shouldSnap && styles.snap
								)}
								d={metersPath}
							/>
							<path
								className={styles.bold}
								d={overlayPath}
								markerEnd={
									mode === 'relative' ? `url(#${markerId})` : undefined
								}
							/>
							<path className={styles.bold} d={activeMeterPath} />
						</svg>
						<Tooltip
							className={styles.overlayLabel}
							style={{left: labelPosition[0], top: labelPosition[1]}}
						>
							{display}
						</Tooltip>
					</div>
				</TweakOverlay>
			)}
		</>
	)
}

// packages/vue/src/InputRotary/InputRotary.vue
<script lang="ts" setup>
import {
	mergeSvgPaths,
	type Rect,
	svgArc,
	svgCircle,
	svgLine,
	unsignedMod,
} from '@tweeq/core'
import {useFocus, useMagicKeys, useWindowSize} from '@vueuse/core'
import {scalar, vec2} from 'linearly'
import {range} from 'lodash-es'
import {computed, ref, useTemplateRef, watch} from 'vue'

import {useMultiSelectStore} from '../stores/multiSelect'
import {useThemeStore} from '../stores/theme'
import {SvgIcon} from '../SvgIcon'
import {Tooltip} from '../Tooltip'
import {TweakOverlay} from '../TweakOverlay'
import type {InputEmits} from '../types'
import {useLastActive} from '../use/use'
import {useCopyPaste} from '../use/useCopyPaste'
import {useCursorStyle} from '../use/useCursorStyle'
import {useDrag} from '../use/useDrag'
import {useElementCenter} from '../use/useElementCenter'
import * as V from '@tweeq/core/validator'
import type {InputRotaryProps} from './types'
import {clampPosWithinRect} from './utils'

const props = withDefaults(defineProps<InputRotaryProps>(), {
	snap: 45,
	angleOffset: -90,
})

const theme = useThemeStore()

const model = defineModel<number>({required: true})

const emit = defineEmits<InputEmits>()

function signedAngleBetween(target: number, source: number) {
	const ret = target - source
	return unsignedMod(ret + 180, 360) - 180
}

const display = computed(() => {
	const revs = Math.trunc(model.value / 360)
	const rot = model.value - revs * 360

	return (revs !== 0 ? revs + 'x ' : '') + rot.toFixed(1) + '°'
})

const initialValueOnTweak = ref(model.value)

const snapMeterRadii: vec2 = [theme.inputHeight * 4, 160]

const $root = useTemplateRef('$root')
const center = useElementCenter($root)

const {
	dragging: tweaking,
	initial,
	origin,
	xy,
} = useDrag($root, {
	dragDelaySeconds: 0,
	onDragStart({xy}) {
		initialValueOnTweak.value = local.value = model.value

		if (tweakMode.value === 'absolute') {
			const p = vec2.sub(xy, center.value)
			const angle = vec2.angle(p) - props.angleOffset
			const diff = signedAngleBetween(angle, local.value)

			local.value += diff
		}

		multi.capture()
	},
	onDrag({xy, previous}) {
		const p = vec2.sub(xy, center.value)
		const pp = vec2.sub(previous, center.value)

		const delta = vec2.angle(pp, p)
		local.value += delta
	},
	onDragEnd() {
		emit('confirm')
		multi.confirm()
	},
})

const {shift, q, a: absoluteModeKey, r: relativeModeKey} = useMagicKeys()
const doSnapKey = computed(() => shift.value || q.value)

const doSnap = computed(() => {
	const radius = vec2.dist(center.value, xy.value)
	return (
		doSnapKey.value ||
		(snapMeterRadii[0] <= radius && radius <= snapMeterRadii[1])
	)
})

const tweakModeByPointer = ref<'absolute' | 'relative'>('relative')

const tweakModeByKey = useLastActive({
	absolute: absoluteModeKey,
	relative: relativeModeKey,
})

const tweakMode = computed(
	() => tweakModeByKey.value ?? tweakModeByPointer.value
)

// Local value before snap
const local = ref(model.value)

const validate = computed<V.Validator<number>>(() => {
	return doSnap.value ? V.quantize(props.snap) : V.identity
})

const validateResult = computed(() => validate.value(local.value))

watch(
	() =>
		[
			validateResult.value,
			tweaking.value,
			tweakMode.value,
			doSnap.value,
			props.snap,
		] as const,
	([result]) => {
		if (result.value === undefined) return

		if (tweaking.value) {
			model.value = result.value
		}

		if (tweaking.value) {
			if (tweakMode.value === 'absolute') {
				multi.update(() => result.value)
			} else {
				const delta = result.value - initialValueOnTweak.value

				multi.update(x => {
					const newX = x + delta
					return doSnap.value ? scalar.quantize(newX, props.snap) : newX
				})
			}
		}
	},
	{flush: 'sync'}
)

useCursorStyle(() => (tweaking.value ? 'none' : null))

const rotaryStyles = computed(() => {
	const rotation = model.value + props.angleOffset
	return {
		transform: `rotate(${rotation}deg)`,
	}
})

const windowSize = useWindowSize()

const overlayBounds = computed<Rect>(() => {
	const margin = 40
	const left = margin,
		top = margin,
		right = windowSize.width.value - margin,
		bottom = windowSize.height.value - margin

	return [
		[left, top],
		[right, bottom],
	]
})

const overlayLabelPos = computed(() => {
	return clampPosWithinRect(initial.value, xy.value, overlayBounds.value)
})

const overlayArrowStyles = computed(() => {
	const p = vec2.sub(xy.value, origin.value)
	const angle = vec2.angle(p) + 90

	return {
		transform: `rotate(${angle}deg)`,
	}
})

function radialLine(angle: number, innerRadius: number, outerRadius: number) {
	const a = angle + props.angleOffset
	return svgLine(
		vec2.dir(a, innerRadius, center.value),
		vec2.dir(a, outerRadius, center.value)
	)
}

const metersPath = computed(() =>
	mergeSvgPaths(
		range(0, 360, props.snap).map(a => radialLine(a, ...snapMeterRadii))
	)
)

const activeMeterPath = computed(() => {
	return doSnap.value && model.value % props.snap === 0
		? radialLine(model.value, ...snapMeterRadii)
		: ''
})

const overlayPath = computed(() => {
	const c = center.value

	if (tweakMode.value === 'absolute') {
		const dist = vec2.distance(center.value, xy.value)
		const angle = model.value

		const innerRadius = theme.inputHeight
		const outerRadius = dist

		return radialLine(angle, innerRadius, outerRadius)
	} else {
		const baseRadius = theme.inputHeight * 4
		const radiusStep = theme.inputHeight * 0.25

		const start = initialValueOnTweak.value + props.angleOffset
		const end = model.value + props.angleOffset

		const turns =
			Math.floor(Math.abs(end - start) / 360) * Math.sign(end - start)

		// Create revolutions
		const revolutions = range(0, turns).map(i =>
			svgCircle(c, baseRadius + i * radiusStep)
		)

		// Create arc
		const arcRadius = baseRadius + turns * radiusStep

		let offsetInTurn = unsignedMod(signedAngleBetween(end, start), 360)
		if (end < start) {
			offsetInTurn -= 360
		}

		const startInTurn = unsignedMod(start, 360)
		const endInTurn = startInTurn + offsetInTurn

		const arc = svgArc(c, arcRadius, startInTurn, endInTurn)

		return mergeSvgPaths([...revolutions, arc])
	}
})

//------------------------------------------------------------------------------
// Multi Select

const multi = useMultiSelectStore().register({
	type: 'number',
	el: $root,
	focusing: useFocus($root).focused,
	getValue: () => local.value,
	setValue(value) {
		local.value = value
		if (validateResult.value.value) {
			model.value = validateResult.value.value
		}
	},
	confirm() {
		emit('confirm')
	},
})

//------------------------------------------------------------------------------
// Copy and paste

useCopyPaste({
	target: $root,
	onCopy() {
		navigator.clipboard.writeText(model.value.toString())
	},
	onPaste: async () => {
		const text = await navigator.clipboard.readText()
		if (!text) return

		const value = parseFloat(text)

		if (isNaN(value)) return

		model.value = value

		multi.update(() => value)
		multi.confirm()
	},
})
</script>

<template>
	<button
		ref="$root"
		class="TqInputRotary"
		:class="{tweaking, subfocus: multi.subfocus}"
		:tweak-mode="tweakMode"
		@focus="emit('focus')"
		@blur="emit('blur')"
	>
		<SvgIcon mode="block" class="rotary">
			<circle class="circle" cx="16" cy="16" r="16" />
			<g
				transform-origin="16 16"
				:style="rotaryStyles"
				@pointerenter="tweakModeByPointer = 'absolute'"
				@pointerleave="!tweaking && (tweakModeByPointer = 'relative')"
			>
				<path
					class="absolute-mode-area"
					d="M 16 16 L 16 32 A 16 16 0 0 0 16 0 Z"
				/>
				<path class="tip" d="M20 16 L30 16" />
			</g>
			<circle cx="16" cy="16" r="7" fill="transparent" stroke="none" />
		</SvgIcon>
	</button>
	<TweakOverlay v-if="tweaking">
		<div class="overlay">
			<svg>
				<defs>
					<marker
						id="arrow"
						markerWidth="6"
						markerHeight="6"
						refX="3"
						refY="3"
						orient="auto"
						fill="var(--tq-color-accent)"
					>
						<path d="M 0 0 L 6 3 L 0 6 Z" />
					</marker>
				</defs>
				<path class="thin gray" :class="{snap: doSnap}" :d="metersPath" />
				<path
					class="bold"
					:d="overlayPath"
					:marker-end="tweakMode === 'relative' ? 'url(#arrow)' : ''"
				/>
				<path class="bold" :d="activeMeterPath" />
			</svg>
			<Tooltip
				ref="overlayLabel"
				class="overlay-label"
				:style="{
					top: overlayLabelPos[1] + 'px',
					left: overlayLabelPos[0] + 'px',
				}"
			>
				{{ display }}
				<span class="arrows" :style="overlayArrowStyles" />
			</Tooltip>
		</div>
	</TweakOverlay>
</template>

<style lang="stylus" scoped>

.TqInputRotary
	position relative
	display block
	width var(--tq-input-height)
	height var(--tq-input-height)
	z-index 1

	&:hover, &.tweaking
		z-index 2

		.rotary
			transform scale(1.8)

	&:focus,
	&.subfocus
		&:before
			content ''
			position absolute
			inset -3px
			border-radius 50%
			border 1px solid var(--tq-color-accent-hover)


.rotary
	width var(--tq-input-height)
	height var(--tq-input-height)
	hover-transition(transform)

.circle
	fill var(--tq-color-accent)
	stroke none

	&:hover,
	.TqInputRotary:focus-visible &,
	.TqInputRotary:hover[tweak-mode=relative] &
		fill var(--tq-color-accent-hover)

	.TqInputRotary:hover[tweak-mode=absolute] &
		fill var(--tq-color-accent-soft)

.absolute-mode-area
	fill transparent
	stroke none

.tip
	transform-origin 16px 16px
	stroke var(--tq-color-input)
	stroke-width 3
	stroke-linecap round

	[tweak-mode=absolute]:hover &
		stroke var(--tq-color-accent-hover)

.overlay
	input-overlay()

	.snap
		stroke-width 2
		stroke var(--tq-color-accent-soft-hover) !important

.overlay-label
	z-index 1001
	position fixed
	transform translate(-50%, -50%)

	.arrows
		position absolute
		inset 0
		color var(--tq-color-accent)

		&:before, &:after
			position absolute
			top 50%
			display block
			width 1em
			font-size 14px
			text-align center
			font-weight normal
			transform translateY(-50%)

		&:before
			right 100%
			content '<'

		&:after
			left 100%
			content '>'
</style>
